serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = {{ .Envs.FRP_SERVER_PORT }}

[auth]
token = "{{ .Envs.FRP_SERVER_TOKEN }}"

[transport]
protocol = "kcp"

[webServer]
addr = "{{ .Envs.FRP_ADMIN_ADDR }}"
port = {{ .Envs.FRP_ADMIN_PORT }}
user = "{{ .Envs.FRP_ADMIN_USER }}"
password = "{{ .Envs.FRP_ADMIN_PASSWORD }}"

[[proxies]]
name = "ssh"
type = "tcp"
localPort  = 22
remotePort = 22
localIp    = "{{ .Envs.FRP_APP_HOST }}"
